#pragma region xtd generated code
// This code was generated by CMake script.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

#pragma once

#include <xtd/xtd>

namespace xtd_tools::properties {
  /// @brief A strongly typed settings class, for storing user and system settings
  /// @details This class was auto-generated by CMake script. To add or remove a member, edit your CMakeList.txt or properties/settings.cmake file then rerun cmake tools.
  /// @remarks See <a href=https://gammasoft71.github.io/xtd/docs/documentation/Guides/xtd.core/settings>Settings</a> for more informations.
  class settings : public xtd::forms::component {
  public:
    /// @brief Initializes a new instance of the xtd_tools::properties::settings class.
    settings() : ::xtd_tools::properties::settings(true) {}

    /// @brief Gets the default instance of settings.
    /// @return The default instance.
    static ::xtd_tools::properties::settings& default_settings() {
      static ::xtd_tools::properties::settings default_settings;
      return default_settings;
    }

    /// @brief Gets the xtd_sources_path user setting property.
    /// @return A xtd::ustring value.
    xtd::ustring xtd_sources_path() const {return xtd_sources_path_;}
    /// @brief Sets the xtd_sources_path user setting property.
    /// @param value A xtd::ustring value.
    void xtd_sources_path(xtd::ustring value) {xtd_sources_path_ = value;}

    /// @brief Reload all properties with the last saved values.
    /// @remarks See <a href=https://gammasoft71.github.io/xtd/docs/documentation/Guides/xtd.core/settings>Settings</a> for more informations.
    void reload() {
      xtd_sources_path_ = settings_.read("xtd_sources_path", xtd_sources_path_);
    }

    /// @brief Reset all properties to their default values.
    /// @remarks See <a href=https://gammasoft71.github.io/xtd/docs/documentation/Guides/xtd.core/settings>Settings</a> for more informations.
    void reset() {
      settings_.reset();
      *this = settings(false);
      reload();
    }

    /// @brief Save all properties.
    /// @remarks See <a href=https://gammasoft71.github.io/xtd/docs/documentation/Guides/xtd.core/settings>Settings</a> for more informations.
    void save() {
      settings_.write("xtd_sources_path", xtd_sources_path_);
      settings_.save();
    }

  private:
    explicit settings(bool load) {if (load) reload();}
    xtd::forms::settings settings_;
    xtd::ustring xtd_sources_path_ {};
  };
}

#pragma endregion
