#pragma region xtd generated code
// This code was generated by CMake script.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

#pragma once

#include <xtd/xtd>

namespace xtd_tools::properties {
  class settings : public xtd::forms::component {
  public:
    settings() : ::xtd_tools::properties::settings(true) {}

    static ::xtd_tools::properties::settings& default_settings() {
      static ::xtd_tools::properties::settings default_settings;
      return default_settings;
    }

    xtd::ustring xtd_sources_path() const {return xtd_sources_path_;}
    void xtd_sources_path(xtd::ustring value) {xtd_sources_path_ = value;}

    void reload() {
      xtd_sources_path_ = settings_.read("xtd_sources_path", xtd_sources_path_);
    }

    void reset() {
      settings_.reset();
      *this = settings(false);
      reload();
    }

    void save() {
      settings_.write("xtd_sources_path", xtd_sources_path_);
      settings_.save();
    }

  private:
    explicit settings(bool load) {if (load) reload();}
    xtd::forms::settings settings_;
    xtd::ustring xtd_sources_path_ {};
  };
}

#pragma endregion
